# 04_복사와 뷰
### 1. 복사와 뷰 - 모두 복사 안함
- 단순한 할당은 배열 객체나 데이터의 사본을 만들지 않음

In [1]:
import numpy as np

In [2]:
A = np.arange(12)

In [3]:
B = A

In [4]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
B.shape = (3,4)

In [7]:
A  # B의 shape를 바꾸면 A의 shape도 바뀜

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
B[::2,] = 0  # 첫 행부터 매 2번째 행의 값을 0으로 바꿈

In [10]:
B

array([[0, 0, 0, 0],
       [4, 5, 6, 7],
       [0, 0, 0, 0]])

In [11]:
A  # B의 데이터를 바꾸면 A의 데이터도 바뀜

array([[0, 0, 0, 0],
       [4, 5, 6, 7],
       [0, 0, 0, 0]])

### 2. 복사와 뷰 - 얕은 복사 뷰(view)
- 뷰는 동일한 데이터를 공유할 수 있는 다른 객체
- **view()** : 동일한 데이터를 보는 새로운 배열 객체를 생성

In [12]:
A = np.arange(12).reshape(3,4)

In [13]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
C = A.view()

In [15]:
C is A

False

In [16]:
C.flags.owndata  # C 데이터는 자기 것이 아님

False

In [17]:
C.shape = (2,6)

In [18]:
C

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
A  # C의 shape를 변경해도 A는 변경되지 않음(다른 모양 같은 데이터)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
A[0,] = [10,20,30,40]

In [21]:
A

array([[10, 20, 30, 40],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
C  # A를 변경하면 C 데이터도 변경됨

array([[10, 20, 30, 40,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

- 슬라이싱하면 뷰가 반환  
- s[:,:] 형식으로 배열을 자르면 뷰가 반환.  
  배열을 자르고 할당할 경우 원본 배열의 값이 바뀜.

In [23]:
A = np.arange(12).reshape(3,4)

In [24]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
S = A[:, 1:3]

In [26]:
S

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [27]:
S[:, 1] = 100

In [28]:
S

array([[  1, 100],
       [  5, 100],
       [  9, 100]])

In [29]:
A  # 주의!!! 배열을 자르고 할당할 경우 원본 배열의 값이 바뀜

array([[  0,   1, 100,   3],
       [  4,   5, 100,   7],
       [  8,   9, 100,  11]])

=> 슬라이싱 하면 뷰가 반환됨, **슬라이싱 후 데이터를 변경하면 원본 배열도 같이 바뀌므로 주의**해야 함!!!

### 3. 복사와 뷰 – 깊은 복사 카피(copy)
- **copy()** : 배열 및 해당 데이터의 전체 복사본을 생성

In [30]:
A = np.arange(12).reshape(3,4)

In [31]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
D = A.copy()

In [33]:
D is A

False

In [34]:
D.shape = (2,6)

In [35]:
D

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [36]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
D[0, :] = [0,0,0,0,0,0]

In [38]:
D

array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  7,  8,  9, 10, 11]])

In [39]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

[정리]  

    - copy()에 의한 복사는 새로운 객체가 된다.
    - view()는 데이터는 공유하지만 shape는 다른 객체가 된다.
      = 에 의한 할당은 같은 객체를 참조한다.
    - 슬라이싱하면 뷰가 반환된다.